"""new decimal

Revision ID: 1167948a8859
Revises: 3b970f1a0d3d
Create Date: 2026-01-15 18:49:04.145261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1167948a8859'
down_revision: Union[str, Sequence[str], None] = '3b970f1a0d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Location_seats', 'cord_x',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.DECIMAL(precision=20, scale=15),
               existing_nullable=False)
    op.alter_column('Location_seats', 'cord_y',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.DECIMAL(precision=20, scale=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Location_seats', 'cord_y',
               existing_type=sa.DECIMAL(precision=20, scale=15),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('Location_seats', 'cord_x',
               existing_type=sa.DECIMAL(precision=20, scale=15),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
